vis-open
It was hard to read with everything on the same indentation level.
=> vis-open: Fix indentation

configure
=> fix linker flags

README.md
Add pkgsrc to "distribution packages" list. I just updated it to v0.2.
=> README.md: Add pkgsrc to the distribution packages list

main.c
"open-file-under-cursor-new-cursor" should be
"open-file-under-cursor-new-window"
=> main.c: correct name of function, cursor to window

README.md
=> add travis-ci build status badge to the Markdown readme

main.c, vis.c, vis.h
=> Fix autoindent when using O

GNUmakefile
`--without-progs` was passed twice
edit: `--disable-database` could be moved to the last line to keep line lengths short
=> remove duplicate argument

main.c
Fix help text for next/prev matches.
=> fix help text for next/prev match

lua/lexers/php.lua
fixes #598 
I updated with keywords and constants from 
[http://php.net/manual/en/reserved.php](http://php.net/manual/en/reserved.php)
=> Updated php

lua/lexers/xs.lua, lua/plugins/filetype.lua
This is a lexer for xs <https://github.com/TieDyedDevil/xs>.
(xs was formerly handled by the rc lexer.)
=> Add `xs` lexer and mappings.

lua/lexers/erlang.lua
Not perfect but a bit better I think.
=> Update erlang syntax lexer.

man/vis.1
Adding an example to the manual how to set and restore marks because I could not figure out how to do so from reading the manual. Maybe I'm being thick butI had to find out by reading the commit message from ad10da5cc
=> Add a key combo example of mark usage

lua/lexers/reason.lua, lua/plugins/filetype.lua
I've added Vagrantfile as a Ruby file extension, .yml as a YAML file extension, and a [Reason ML parser](https://reasonml.github.io/) based on the OCaml parser.
=> Lexer improvements (RFC)

lua/lexers/ruby.lua
~I made one commit per function, but let me know if you prefer me to squash those.~
Commits squashed
=> lexers: add extend, include, module_function and require_relative to ruby

README.md
One question about the part on Lua extensions, namely:
> There is also a Lua API for in-process extensions.
Does "in-process" mean "runtime"?
=> Improve comma usage and hyphenation in intro

config.def.h
=> change case in visual mode with u and U ( vim comp )

lua/lexers/ansi_c.lua
- Fixed order of rules.
- Some “keywords” were identified as “type”, now corrected.
- Added compiler-specific common __keywords.
- Added boolean and additional integer constants.
- Added support for number suffixes.
- Removed “#if 0“ comments, because it needs some work on the else
branch. Now it just makes things unreadable.
=> lexers: update ansi_c

vis.c
=> vis: don't draw colorcolumn after the end

sam.c
A vis.events.FILE_SAVE_PRE callback may mutate the file text,
making the original range passed to cmd_write incorrect.
It is unclear how to realign the range after the callback
is done for the cases where an active selection in visual mode
is present or an explicit range like :1,2w! was specified.
However, this commit resolves the issue for the case where
the whole file is expected to be written.
Tests are in https://github.com/martanne/vis-test/pull/19.
Closes #806
Closes #715
Updates #652
=> sam: re-take range after pre-save hooks are run

lua/lexers/julia.lua, lua/plugins/filetype.lua
=> Add Julia lexer

man/vis.1, sam.c, vis-cmds.c, vis-core.h, vis-prompt.c, vis.c
Add a global ignorecase boolean option.  When set add REG_ICASE to cflags
when calling text_regex_compile().
=> Add ignorecase option

lua/lexers/routeros.lua, lua/plugins/filetype.lua
Add a lexer for Mikrotik RouterOS scripts.
https://wiki.mikrotik.com/wiki/Manual:Scripting
=> lexers: add Mikrotik RouterOS script lexer

man/vis.1
=> distinguish between immediate and waiting operators

vis-lua.c
This enables launching a subprocess from a Lua plugin that doesn't act as a filter. It is useful for running interactive programs like nnn as a file picker where the picked file name is provided in a temporary file and not piped back to vis, see https://github.com/captaingroove/vis-nnn.
=> [Lua API] enable nil parameters in vis:pipe() for File and Range

vis-lua.c
The only place where this behaviour was encountered was in
`file_lines_iterator()` and it was just being worked around.
~~There was also likely a bug in the case that `addr` was `NULL` since 2
values would be popped from the stack instead of just 1. It is possible
that the case is never hit though.~~
Edit: Ignore that last part. It would hit the `lua_argerror()` branch in that case.
=> vis-lua.c: stop obj_ref_get() from leaving the lua stack modified

Dockerfile
Just a version bump, no changes required.
=> build: update alpine in docker build to version 3.20

lua/themes/base-16.lua
This closes https://github.com/martanne/vis/issues/1196.
=> Add additional html style tags to base-16.lua

lua/vis.lua
Reported-By: aimixsaka <aimixsaka@gmail.com>
Fixes #1215.
=> lua: fix table member reference in set_syntax

Dockerfile
Just a version bump, no changes required.
=> build: update alpine in docker build to version 3.21

ui-terminal-curses.c, ui-terminal-vt100.c, ui-terminal.c
=> curses ui: fix default color detection

man/vis.1
Found this while reading the manual.
=> vis.1: fix typo

Dockerfile
Just a version bump, no changes required.
=> build: update alpine in docker build to version 3.22
