config.def.h
text.c
vis.c
window.c

The result of trying out vis on the vis source code: Some small fixes and the addition of the :x vim command which I always use instead of :wq or :q

Small fixes, add :x

---

README
editor.h
vis.c

A rudimentary implementation of autoindent in the vim "copyindent" style.

implement rudimentary autoindent

---

config.def.h

The spec is here: http://daringfireball.net/projects/markdown/syntax
Currently, it doesn't support Setext headers and hard-wrapped quotes.
Also, the colours are ugly, feel free to implement a better scheme.

Add rudimentary markdown syntax support

---

config.def.h

Here is a syntax highlighting definition for the journal format used by [ledger](http://ledger-cli.org/).
vis is great for working with ledger journals because of how fast it is at opening and manipulating the large journal files.
I added two more color definitions, to further enrich the visual experience.

Add syntax rules for Ledger

---

config.def.h

A fix for issue #22
Highlighting for http://www.ledger-cli.org/3.0/doc/ledger3.html#Example-Journal-File is the same before fix (compiled in Linux) as after the fix (compiled in Linux and OS X)

Change ledger syntax regex to work with BSD regex

---

config.mk

Since we're in 2015 now, I added some hardening flags.

Add hardening flags for gcc and clang

---

vis.c

close(fd) can't have a negative fd parameter

Fix coverity issue 12388

---

ui-curses.c

`use_default_colors()` needs to be called before the first `refresh()` call to prevent a black flicker when vis first loads. This is because ncurses loads with a black background by default.

Prevent black flicker on load

---

config.def.h

This commit adds javascript and json syntax highlighting. I know it would complicate things but maybe splitting out syntax highlighting from config.def.h would be a good idea.

Add javascript syntax highlighting

---

Makefile

This fixes `make debug` on OpenBSD (and possibly other systems) where
/usr/bin/make isn't GNU make.

Use $(MAKE) instead of directly calling `make`

---

config.def.h

Syntax highlighting compatible with GNU APL.
http://www.gnu.org/software/apl/
For sample *.apl files, see (for example)
https://github.com/TieDyedDevil/apl-pkg
... and some of the projects linked from:
http://www.gnu.org/software/apl/Community.html

Add APL syntax highlighting.

---

vis.c

The buffer `input_queue` was not released at exit. This patch fixes the leak.

vis: free input_queue at exit

---

Makefile

This is basically the same as #49
This fixes `make debug` on OpenBSD (and possibly other systems) where
/usr/bin/make isn't GNU make.

Makefile: Use $(MAKE) instead of directly calling `make`

---

vis-open

If vis-open is placed in a user's PATH and executed then $0 will be
vis-open's absolute path:
```
$ vis-open -h
usage: /usr/local/bin/vis-open [-h] [-p prompt] [file-pattern]
```
This isn't very pretty, so use basename(1) on $0 when printing:
```
$ vis-open -h
usage: vis-open [-h] [-p prompt] [file-pattern]
```

vis-open tweaks

---

.gitignore

From `man gitignore`:
```
o   A leading slash matches the beginning of the pathname. For example,
"/*.c" matches "cat-file.c" but not "mozilla-sha1/sha1.c".
```

gitignore: Fix pattern

---

view.c

Vis currently displays the ASCII-127 (DEL) character as `^M-?`, whereas vim (and other editors) display this character as `^?`.
This commit updates vis to display this character as `^?`.

Display ASCII-127 (DEL) character as ^?

---

view.c
view.h

Marc pointed out in #173 that there is an issue with displaying NUL bytes.
This commit updates vis to specify the NUL byte column width as 2, so that vis treats NUL bytes like other non-printable characters.
Also fixed some typos in the Cell struct comments.

Display NUL bytes correctly

---

config.def.h

`ib` was alised to `ib`, changed this to `i(`.

recursive ib fix

---

config.def.h

Update vis to support these motions which are available in vim.

Add + and - motions to vis

---

view.c

Workaround for #199
4-bytes character used as longest according to [RFC3629](https://tools.ietf.org/html/rfc3629#page-4)

Fix for visual bug with view size when text contains multibyte characters.

---

Makefile

We want vis to be rebuilt when configuration changes, so make vis depend
on config.mk.

configure: make vis depend on config.mk

---

configure

The `+=` assignment operator is not required to be supported by a POSIX shell.

Remove bashisms from configure script.

---

README.md

vis has been packaged for Source Mage GNU/Linux, one of the oldest Linux distros, aimed at high flexibility in customization, while building packages from source.

added link to new SMGL package for vis

---

vis-lua.c

Vis should look for files in `$XDG_CONFIG_HOME/vis`, not just `$XDG_CONFIG_HOME` directly.

Fixed bug, use $XDG_CONFIG_HOME correctly

---

Makefile
vis-menu.1
vis-menu.c

For starters, here's a manpage for vis-menu. It's not based on the slmenu one, it's completely fresh (although I did double-check the original to make sure I understood all the key-bindings).
You might want to edit the manpage before committing it, to add the slmenu and dmenu authors to the "AUTHORS" section, or to remove the key-binding descriptions if you think it'll be too annoying to keep it in sync with the code.
Also, I removed the "Insert"/"Control-Y" code from vis-menu, since it clearly wasn't hooked up to anything. The slmenu manpage claims that keybinding pastes from the X11 clipboard, but it doesn't do that now.

Add a `vis-menu` manpage

---

vis-open

Rather than try to loop manually and build up a path, this new version exec's itself for each new directory scanned. Functional changes include:
- We `set -e` at the top of the script, so any surprising permission-denied errors will automatically cause the script to exit with a helpful error message.
- We now support the GNU "--" convention for splitting options from filename arguments, just in case somebody happens across a directory with a file named "-h" or "-p".
- If launched with a single filename parameter, we automatically return it - if somebody writes ":e somepattern*" and it matches exactly one file, we might as well open it directly.
- If we select a single filename parameter, we use `realpath` to build an absolute path for it - much more reliable than trying to build up a path …

Rewrite vis-open to be more robust.

---

lexers/README.md

`vis.filetypes` can be found on [line 72 of `vis.lua`](https://github.com/martanne/vis/blob/master/vis.lua#L72), but is not present at all in lexer.lua.
Fix `lexers/README.md` to avoid further confusion.

Fix filetype table link in lexers/README.md

---

vis.lua

I just thought filetype detection could be better than simply matching filename extension :)
What was done:
• ignoring `~`, `.bak`, `.orig` and other extensions that are not bound with any file format 
• filename patterns (full filename match against lua pattern);
• shebang detection (application name match);
• custom detection functions.
Benefits:
• scripts with no file extension will be correctly syntax-highlighted;
• xml-based files like `.iml` or others (millions of them) will be syntax-highlighted even if particular extension is not listed;
• it is possible to add syntax highlight for mercurial commit message editor in future (its filenames are like `hg-editor-XYZXYZ.txt` and they couldn't be matched without pattern-based detection).

Better file type detection: full filename patterns, shebang, custom detector functions

---

vis-complete

Entering a file path into the command prompt containing a forward slash character causes the sed command on line 33 to be invalid. For example, open vis in the root of the repository and on the command prompt enter:
```
:e lexers/
```
Then entering `<C-x><C-f>` causes an error message from sed.
This PR updates the sed command to use the pipe delimiter instead.

Harden vis-complete

---

vis-complete

This PR improves vis-complete in the following ways:
- no more repeated shell-evaluation, so shell-sensitive characters in the pattern can't cause problems.
- the pattern is properly quoted before being handed to `grep`, so regex-sensitive characters can't cause problems
- the pattern is properly quoted before being handed to `find`, so glob-sensitive characters can't cause problems
- just as before, giving a relative path will complete relative to the current directory—but now, giving an absolute path works too
This code uses arithmetic expansion (`$(( ))`) but that's [definitely POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_04).

vis-complete improvements

---

main.c
vis-complete

- Update `vis` to provide full file path to `vis-complete`.
- Update `vis-complete` to expand tilde to `$HOME` when it's the first character in a file path.
- Fix issue with `vis-complete` producing incorrect output for relative file paths. The `PATTERN` variable cannot be modified in a pipeline command as each command in a pipeline is run in its own subshell. This caused the value of `${#PATTERN}` to be incorrect for relative paths. This is resolved by modifying `PATTERN` before the pipeline is run.

File completion updates

---

Makefile

Alternatively, these dates should probably be added the man pages themselves so they reflect the date the document was written, not when it was installed.

Fix date in man pages

---

vis.1

Here we go.  A much more complete `mdoc` formatted man page.
I used the [`mdoc` man page](http://mdocml.bsd.lv/man/mdoc.7.html#Bd) for documentation, and the [tmux man page](https://raw.githubusercontent.com/tmux/tmux/master/tmux.1) as a model.
Does it look ok to you?  I tried to follow the standards and keep semantics, as I never wrote `mdoc` before.
I did not remove the content from the README yet.

Man page from the read me

---

vis-clipboard.1
vis-menu.1
vis-open.1

They now pass `mandoc -Tlint` (the BSD manpage renderer) and `man --warnings=w` (the GNU one).

man: Make vis-{clipboard,menu,open} manpages lint-clean.

---

.gitignore
GNUmakefile
vis-single.sh

This allows to create a self extracting executable. The standalone
binary and lua files are extracted to /tmp/.vis-XXXXXX, vis is started
with the given command line arguments, finally temporary files are
removed.

single: allow to build self-extracting executable

---

GNUmakefile

We already did this change for acl (commit cc551cb0). In attr it shows
slightly different symptoms and happens for parallel builds only. The
fix is the same.

standalone: work around borked dependencies in attr

---

GNUmakefile
Makefile

We had several elf executables that were not stripped properly. Move the
filenames to a dedicated variable and use that to not miss anything.

build: properly strip elf executables

---

main.c

The character following a movement_key command should not be subject to
keymap translation since it is used to find characters in the document.

Disable keymap for movement_key character

---

lua/lexers/bash.lua

This allows lines like
: ${FOO:="${bar}/baz"}
to be highlighted correctly (without the nesting, the " after baz will
start a string that messes up the rest of the file.

Allow {} to be nested in shell variables

---

vis-lua.c

I added this to write a plugin that executes commands in all windows. Tested with
```
require('vis')
local module = {}
function module.update()
local active_window = vis.win
for win in vis:windows() do
vis.win = win
if win == active_window then
vis:command('set relativenumber on')
else
vis:command('set number on')
end
end
vis.win = active_window
end
return module
```

vis-lua: make vis:win assignable

---

man/vis.1

I propose formatting change for `vis.1`:
- [`Ad`](http://man.openbsd.org/mdoc#Ad) for register and command address
- [`Ic`](http://man.openbsd.org/mdoc#Ic) (Internal or interactive command) for keybindings and all `:commands`
- [`Rs`](http://man.openbsd.org/mdoc#Rs) for articles reference at the end.
- Using more compact lists for keybindings (`.Bl -compact`).
- Fix all `mandoc -Tlint ./man/vis.1` warnings.
- Homogenize the source.
You may ask for any edit you want me do apply before the merge, or simply refuse if you dislike.

freshen vis.1

---

lua/lexers/forth.lua
lua/plugins/filetype.lua

Noticed the highlighting for Forth files was vastly inconsistent with the [latest national standard](http://lars.nocrew.org/forth2012/core.html) so I made the appropriate changes in lua/lexers/forth.lua and added another common Forth file extension to lua/plugins/filetype.lua. If there's a worry about diverging from upstream Scintillua, I can try to submit the changes there as well.

Add support for ANS Forth 2012 highlighting

---

man/vis.1

The double quotes were visible in the formatted output.

Fix formatting in man page

---

util.h

On GNU Hurd systems PIPE_BUF and PATH_MAX are not defined, and
the compilation fails. This patch defines them if they aren't.

Fix compilation on GNU Hurd systems

---

Makefile

Giving tar the parameter '--sort=name' sorts direcory entries, but keeps
single files as-is. So instead sort the list retrieved by find.
Works for me. [TM] :D

build: produce reproducible self contained executable

---

lua/themes/solarized.lua

Line numbers and EOF markers currently look the same as regular text. This makes a file in which each line starts with a number or tilde visually indistinguishable from a file with line numbers or EOF markers enabled.
This PR tweaks the theme to add a "gutter" background familiar from other editors and make the foreground colors of line numbers and EOF markers less bright.

Improve appearance of line numbers and EOF markers

---

man/vis.1
sam.c
view.c
view.h
vis-cmds.c
vis-prompt.c
vis.c

Allows the user to type
```
:set show-eof off
```
to hide the tildes used as placeholders for empty lines.
It appears that such an option was already planned because the constant `UI_OPTION_SYMBOL_EOF` was already present in the code, it just wasn't implemented.

Add option to hide EOF marker

---

Makefile

No longer needed after standalone build target was removed.

Remove conditional initialization from Makefile

---

man/vis.1

As noted on mdoc(7), in groff  "Lk only accepts a single link-name argument; the remainder is misformatted.
The quotes makes groff treat the title as a single argument.
Note that double quotes where originally used, but where remove in
https://github.com/martanne/vis/commit/bee050696651d7740a54644f11adf21825a8c7f2#diff-1b1a076db28be546dfe17f39e05e60e1L1292

vis.1:  Surround with quotes link-name arguments of .Lk

---

lua/plugins/filetype.lua

Both VB and LaTex use .cls file extensions. It should be a much more
reasonable default to assume LaTex syntax.
Unless there is some reasons i don't know about, it seems more sensible to me that LaTex has higher priority than Visual Basic.

Reassign .cls file extension to latex

---

lua/lexers/php.lua

This allows to end PHP code sections. Otherwise token is treated as part of the comment and parser continues to parse whatever is after.

PHP lexer: stop line comments right before ?>

---

lua/plugins/complete-filename.lua
vis-complete
vis-lua.c

The common dirname part makes it harder to spot the right file, and fewer entries can be visible at once.
With only basenames, one can see quite a few more entries, and know in advance how many key presses (roughly) it would take to get to the desired file.

vis-complete: Show just basenames in vis-menu

---

ui-terminal-curses.c

In ncurses 6.1, the TERMINAL structure was updated[0] to store data in `int`
instead of `short`, and terminfo definitions for 256-color terminals were
updated from `pairs#32767` to `pairs#0x10000`.
However, since vis stores the value of COLOR_PAIRS in a short (ncurses
internally stores it as an int), it is now overflowing into negative, breaking
color support completely.
The standard `init_pair` entry points still use `short` for their parameters, so
just restrict the pairs to `SHRT_MAX` during allocation.
[0] http://invisible-island.net/ncurses/announce-6.1.html#h4-new-library

Support COLOR_PAIRS > SHRT_MAX

---

lua/plugins/complete-filename.lua
vis-lua.c
vis-open

I've had some issues with vis-open and filename completion. As an example, try opening vis in your home directory and typing `:<Tab><Tab><Tab>`. You should end up with something like: `/home/$USER//:***`.
When the shell cannot find any matching files, the glob is not expanded, and vis-open will return the absolute path of the current working directory (because `dirname` prints `.`), followed by the filename, followed by a literal `*`. This commit checks that the final path actually exists, and if not, exits with status 1.
It also uses `text_object_longword` instead of `text_object_word` for the range to match, so that absolute paths are accepted, and replaced properly (else it only matches back to the first '/', and replaces from there. For example, in insert mode, try to  enter …

vis-open: fix for absolute and non-existent paths

---

configure

The current code was printing a false "no" for the whole section:
```
checking for Lua statically linked liblpeg... no
checking for static lua5.3-lpeg... no
checking for static lua5.2-lpeg... yes
```
while it actually applied to only one of the checks -  the simple `-llpeg` one.
I reordered this section to be line-for-line analogous to the Lua section at [configure#L445](/martanne/vis/blob/a09d4d17839ff5a6707913fec696f24e849440b4/configure#L445).
This also made it check for more possible library files.

configure: Improve LPeg detection

---

lua/plugins/filetype.lua

Add plist, a xml filetype used by Apple

add plist (xml) filetype

---

lua/plugins/filetype.lua

`filetype.lua` currently doesn't recognize shell scripts if they are marked as executable (`chmod +x`). This pull request fixes that by adding `application/x-shellscript` as a MIME type associated with the `bash` file type.

vis-lua: add file type detection for executable shell scripts

---

lua/plugins/filetype.lua

Otherwise, a file like `passwd.c` will match both ansi_c and dsv.
The one that gets chosen depends on the iteration order of table,
which is non-deterministic.

filetype: Match known filenames exactly

---

lua/lexers/text.lua
lua/plugins/filetype.lua

It's a text editor, so I think we can surely fallback to “text”–when applicable–instead of using nothing no lexers.
Because of how vis works, it's not a lucky case if you have any of `show-*` set and no lexers are used, because then these replacement characters will seem part of the text.

Minor improvements around text lexer and detection

---

lua/lexers/bash.lua

Or else the following:
<<EOF
....
EOFXYZ
parsers incorrectly.

Heredoc delimiter should end with a newline

---

lua/themes/solarized.lua

When the terminal has a solarized theme, vis's theme does not need to set the background and foreground again. This is particularly useful with the solarized patch for st that allows switching the theme between light and dark on the fly, now vis's theme reflects that switch too.
Plus for issues related to setting the background color correctly, this is a work around - just set the term bg to solarized and the theme works.

solarized themed terms do not need bg and fg set again

---

text-motions.c

vis: fix search wrapping bugs

---

Dockerfile
Makefile

Commit 50b0a580105ac976a1c95df9441d898d7a652bfb updated Alpine docker
image, however this broke building with acl support. The static libacl
moved to its own package, so just install that.

build: install static libacl for docker builds

---

man/vis.1
sam.c

Per [this](https://github.com/martanne/vis/pull/791#issuecomment-577598166) discussion:
No need to explicitly specify "lay" as an abbreviation, since "layout" already makes it available via prefix logic.

remove redundant layout option abbreviation

---

text-motions.c

The special characters array doesn't contain the tab character thus causing issue #711.
By adding the tab character to the array, quotes are matched correctly across tab characters, too.
Although much less used, other white space characters such as \v, \f, and \r should perhaps be added as well.

add tab character to special characters array

---

lua/lexers/xml.lua

The new pattern isn't perfect, but the old one wasn't either.
One of its purposes was to highlight 123, but not 456 below:
```xml
<tag attr=123>text=456</tag>
```
Both the new and the old pattern can be tricked.
Here, 123 is not recognized as a token:
```xml
<tag glitch=">" attr=123 glitch="<">text=456</tag>
```
You can test it by positioning the cursor over one of the numbers and hitting `dii`.
If the _whole_ number is deleted, then it's recognized as a token.
(At least in the themes I use, numbers, even when recognized as such, are not highlighted any differently than text...)
Edit: forgot to mention, this is about issue #603.

lexers: XML performance improvement

---

lua/plugins/filetype.lua

SWI-Prolog [prefers ".pl" and ".pro" extensions](https://www.swi-prolog.org/pldoc/man?section=projectfiles), in that order. It doesn't mention the current extension, ".prolog", however, loads files with this extension without issue.

filetype: add more Prolog filename extensions

---

ui-terminal-curses.c
ui-terminal-vt100.c
ui.h
vis.c

eg. if your long line is a comment with green fg, and you set your
column color bg red while not specifying the fg, then the result is
green fg on red bg.
Prior to this change the result would be default fg on red bg, thus
one char in the long line of green text would look odd/wrong.
Of course if you do explicitly set the column color fg to default in your
theme then the result will not be what you expect - ideally we need
an UNSPECIFIED color type instead of relying on DEFAULT.
The `#if CONFIG_CURSORS` block is not ideal but I'm not sure what would be the right place to put it as currently all those defines are in other source files - is there a reason they're not in a header file?

color-column: Don't change fg/bg if not set explicitly

---

vis.c

Currently vis defaults to rendering a single cursor using the secondary cursor color theme style - not sure how others feel about it but to me it makes more sense that it should be the primary, since there are no secondary cursors visible.
So that's what this patch does - your main cursor is always the same color, and any additional cursors are colored different.
If people disagree then perhaps we can add an option to toggle this behavior?

Set single cursor style as primary, not secondary

---

configure

This is required to build with lua 5.4.x.

build: define LUA_COMPAT_5_3

---

lua/plugins/filetype.lua

Added .ts (typescript) as a javascript filetype, as typescript is a superset of javascript it seem to work ok until it gets its own lexer.

lexers: add .ts as a javascript (until typescript gets its own)

---

lua/plugins/filetype.lua

This covers other detection, so make sure to match it in
last resort only.

filetype: do not match text/plain too early

---

lua/vis.lua
main.c
vis-core.h
vis-lua.c
vis-lua.h
vis.c
vis.h

It allows to implement custom stuff such as mouse pointer or paste mode entirely in Lua.
In (neo)Vim, stuff like this is often hacked in really awkward and conflicting `map` fashion bound to scripts. I don't think doing so is wise as CSI are not really user input, but rather a state signal of the terminal emulator. Further complicated by that the CSI command itself is not actually a prefix code, but a last character in sequence (with variable data inbetween), making most of map-like binding useless.
An example of paste mode in visrc with this patch:
```lua
require 'vis'
local vis = vis
local io = io
local _ENV = setmetatable({}, {__index = function(t,k) return _ENV[k] or vis.events[k] or vis.modes[k] or function(...) return vis[k](vis, ...) end end })
command 'set expandtab'
command 'set …
```

Pass up terminal CSI as events to Lua.

---

lua/plugins/filetype.lua

Node.js uses `.mjs` and `.cjs` extensions, both are regular javascript.

filetype: and Node.js module extensions

---

lua/plugins/filetype.lua

There is no .lily file but there is a .ily file in lilypond for stylesheets. 
They are like css for lilypond. I tested with the command `set syntax lilypond` on a .ily file.
The lilypond lexer works great for .ily too.
See here:
http://lilypond.org/doc/v2.18/Documentation/learning/style-sheets

lua: fix typo in lilypond file extension

---

lua/lexers/meson.lua
lua/plugins/filetype.lua

A simple lexer for the Meson build specification file syntax.
For simplicity keyword arguments were excluded from highlighting.
The lexer was build using the [meson reference manual](https://mesonbuild.com/Reference-manual.html) for version 0.56.0.

lexers: add meson build file lexer

---

lua/lexers/bash.lua

If a here-doc start delimiter begins with "-", then spaces are allowed
to come before the closing delimiter.
This patch fixes what would otherwise be parsed incorrectly:
<<-EOF
....
EOF

Heredocs with "-" can have spaces before closing

---

array.h
buffer.h
sam.c
text-io.c
text-motions.h
text-objects.h
text.c
text.h
ui.h
view.c
view.h
vis-core.h
vis-lua.c
vis.c
vis.h

This pull request fixes typos in comments that I spotted reading through the code.

fix comment typos in vis.h

---

lua/lexers/bash.lua

f4f0f5b allowed "<<-EOF" heredocs to be parsed correctly, but it
introduced a bug that made the lexer fail when the beginning of a
here-doc was the last string in a file (optionally followed only
by blanks).
In order to fix this, move everything regarding "delimiter" within
the block that is executed only if "delimiter" is not nil.

lexers: fix bug in bash lexer for last here-doc

---

lua/plugins/filetype.lua

These two commits add support for APKBUILD, .ebuild, and generic Makefile (with shebang) files in the filetype plugin.

filetype: Add recognition for APKBUILD, .ebuild, and general Makefile shebang (debian/rules).

---

lua/vis.lua

`vis:pipe` returns an integer status.

Fix luadoc to use ~= for status

---

sam.c

When the cmd closes the window the window pointer gets freed along the way. We can't use win->next to update the loop variable if sam_execute() has been called. Instead we can store win->next early and use that variable to continue the loop.
fixes #1090

fix use after free in cmd_files()

---

vis.c

Currently inner and outer text objects both behave exactly the same for linewise operations. I think it would make a lot more sense to limit inner text objects to only the lines contained within the range. So for example right now `>i{` and `>a{` from with in this if
```c
if (linewise && (a->textobj->type & TEXTOBJECT_DELIMITED_INNER)) {
r.start = text_line_next(txt, r.start);
r.end = text_line_prev(txt, r.end);
}
```
both result in
```c
if (linewise && (a->textobj->type & TEXTOBJECT_DELIMITED_INNER)) {
r.start = text_line_next(txt, r.start);
r.end = text_line_prev(txt, r.end);
}
```
With these changes `>i{` would only affect the lines contained inside like so:
```c
if (linewise && (a->textobj->type & TEXTOBJECT_DELIMITED_INNER)) {
r.start = text_line_next(txt, r.start);
r.end = …
```

Improve behavior of inner text objects when working linewise

---

.github/workflows/man.yml
man/vis.1

I've always found this wording a bit confusing.  I think the way I understand it in my mind is opposite to the current wording. By switching to rows and columns it should clear up the confusion.
(horizontally) and (vertically) were kept to be consistent with the 'v'
mnemonic and with the enum labels in the code.

reword the :[v]split and :[v]new descriptions in vis.1

---

man/vis-clipboard.1
vis-clipboard

this is mostly useful for the internal vis usage and makes both `*` and `+` ~buffers~ registers work on macOS/cygwin.
fixes: #1067
Note: I can't test this and I want others opinions on it. I don't even think the deleted check is correct right now since who is to say what the user meant when they specified `--selection` on macOS/cygwin.
Edit: I meant registers not buffers

vis-clipboard: don't fail when sel is primary on unsupported platforms

---

Makefile

We can make `od` skip the address radix, so `sed` does not
need to remove it.

build: simplify generating single payload

---

vis-cmds.c

Print keybindings starting with space correctly

---

sam.c
ui-terminal-curses.c
ui-terminal-vt100.c
ui-terminal.c
ui.h
vis-cmds.c
vis-lua.c
vis-registers.c
vis.c
vis.h

When running a fullscreen program (curses) with vis:pipe() the terminal is not restored correctly. There's no way to automatically detect whether a program has to be run in shell or fullscreen mode, so a parameter needs to be added to vis_pipe_*() and also vis:pipe() in the Lua API. This is useful for e.g. running interactive programs like nnn as a file picker, see https://github.com/captaingroove/vis-nnn.

Properly restore terminal after running fullscreen program

---

vis-lua.c

fixes #1107
Note: This is a bit of a hack and I don't think it should actually be
applied. It only works when file is changed via the `else` branch of
the check that follows.
I will work on a proper fix later if no one has anything better.

vis:pipe(): don't segfault if vis->win isn't present

---

man/vis.1
sam.c
view.c
view.h
vis-cmds.c

Hello, this pull request adds soft word wrapping (`linebreak` in vim) support to vis. In addition, it defines an option to change the visual line length instead of always using window width for the maximum line length. The latter was made trivial by my code rewrite.
It is a lot of pain to write LaTeX and Markdown documents without proper word wrapping support in the editor. This option is something that makes your life much easier and is supported by nearly all other text editors. In fact, a similar functionality was requested by #142, but on the contrary to that proposal, this pull request only affects the way lines are displayed on screen and doesn't modify the underlined character data.
- `breakat / brk` specifies a list of characters after which the editor may decide to wrap the line …

Soft word wrapping

---

vis-open

It might be more comfortable to navigate through the files
arranged vertically.
Add ability to specify VIS_OPEN_LINES environment variable
which is passed to vis-menu as -l option.
It would be better to add vis option for this to set it
via lua config, but it might be added later.
Signed-off-by: Vadym Kochan <vadim4j@gmail.com>

vis-open: allow to show files vertically

---

man/vis.1
sam.c
ui-terminal.c
ui.h
view.c
view.h
vis-cmds.c
vis-lua.c
vis.h

the first point of this commit is to allow all options to be read from lua. this has a number of uses for plugin writers. they are grouped into a couple of tables depending on what they control: `vis.options`: table with global configuration
`win.options`: table with window specific configuration
the second point is to allow you to set all these options as if they were simply lua variables. technically this is already possible by using `vis:command("set ...")` but personally I think this interface is cleaner. Note that this already possible for some things like the current mode (eg. vis.mode = vis.modes.VISUAL). examples: `vis.options.ai = true`
`vis.options.brk = " !?."`
there are a number of related issues and pull requests:
closes #803: Lua API: let plugins read the values of options …

Lua API: access and set all available options

---

configure

the latest if more than one installed. This change is specifically needed for FreeBSD.
modified:   configure

Added lua-5.4 to list of libluas used to find installed lua version, or

---

vis-lua.c

When passing an invalid handler type (such as nil) to Vis:map/Window:map, the editor would map the key to an empty (zeroed) KeyBinding that would cause itself to become unresponsive when processing the corresponding key.

vis-lua: raise an error when mapping to invalid handler types

---

lua/plugins/complete-filename.lua

There are probably more things to simplify but at least this makes it easier to see what exactly is different between `<C-x><C-f>` and `<C-x><C-o>`.
closes #1146
Comments on how to simplify this more would be appreciated!

lua: refactor complete-filename plugin

---

lua/vis-std.lua

This caused a warning on startup when using Apple Terminal. I have no clue what this does and whether it is still necessary, but at least now it is silent.

Update deprecated change-256colors in vis-std.lua

---

main.c

Use correct apostrophe in error message. E.g. when trying to open a directory.
BTW: I noticed that the error messages varies a bit, e.g. we use both "Can not", "Can't", "Could not", "Failed to". Perhaps these could be expressed in one way? I suggest "Can not" (as it is the most used). BTW "Cannot" is also a normally used word to express this.

use correct apostrophe in error message

---

lua/vis.lua
main.c
ui-terminal.c
ui.h
vis-core.h
vis-lua.c
vis-lua.h
vis.c
vis.h

This pull request essentially exposes the new style handling from PR #1154 to the Lua API, allowing plugins to make direct changes to cells using a new `Win` method, `Win.style_pos`.
It also adds a new style constant, `STYLE_LEXER_MAX`, which provides a reliable way of defining new user styles without needing to interact with the lexer.
Finally, a new event in `ui-terminal.c`, UI_DRAW, allows plugin developers the opportunity to override all previous styling. This allows for the creation of new UI elements entirely within the Lua API. This event is emitted at quite a low level (outside of vis.c and in ui_draw, right before the backend blit function), so I'd like opinions on whether it's even a good idea to have events outside of vis.c. In my opinion, it's a reasonably UI-specific event …

RFC: Direct access to cell styling via API

---

lua/plugins/complete-filename.lua

This allows for example to complete file names in markdown images.
E.g.:    `![](pic<C-x><C-f>`    will complete the file name starting with pic.
Previously it would have detected the `'['` as prefix and looked for files starting with `](pic`.
Maybe I can sneek this in before #1185. This is sitting on top of my tree for quite some time now and I have not encountered any regression using the biggest possible match with our regex.
Apparently, my email setup is currently broken hence the github pull request.

lua: complete-filename: use biggest possible prefix

---

configure

Enables lpeg when building on Debian 12 with `apt install lua5.4 lua-lpeg`.

configure: check for 'lua5.4-lpeg' too

---

vis.c

Since the last release (v0.9), my theme configuration has stopped working: the color of the primary selection cursor no longer matches the ``lexer.STYLE_CURSOR_PRIMARY`` setting. 
This patch fixes this issue.

fix primary cursor color display

---

Makefile
event-basic.c
main.c
sam.c
ui-terminal-curses.c
ui-terminal-vt100.c
ui-terminal.c
ui-terminal.h
ui.h
view.c
view.h
vis-cmds.c
vis-core.h
vis-lua.c
vis-lua.h
vis-marks.c
vis-modes.c
vis-motions.c
vis-operators.c
vis-prompt.c
vis-registers.c
vis.c
vis.h

I was growing tired of trying to debug things in vis when everything had to jump through many levels of redirection because all of the core structures were opaque. So I went through and cleaned all that up. While I was at it I shuffled some things around so that now when you want to add a new event to lua you don't need to define a stub function for when lua is disabled.
The only functional change that should have happened is that the QUIT event now happens after all windows have been closed and their files freed. Everything else should be the same as before.
Obviously a 450 line reduction in code is nice and on my system the binary size was also reduced by ~10kB. At runtime there is probably a minor performance benefit and lower memory usage but I didn't really measure those.
I'm still …

RFC: Largish Cleanup and Refactoring

---

.github/workflows/macos.yml
.github/workflows/ubuntu.yml

Install busted in the CI pipelines to run the included lua tests.

ci: install busted to run lua tests

---

.github/workflows/ubuntu.yml

Github CI ubuntu-20.04 runner image deprecated, seen in https://github.com/actions/runner-images/issues/11101

ci: drop ubuntu-20.04, deprecated
